language: node_js
node_js:
- '6.1'
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIGPUEZDFROYEAUWA
  secret_access_key:
    secure: vCGwb4E0FM2iiAb/LU05adtt4vyqr4Djv5024hLuiA/aN6iJPzn6qqskRgZHNXEULF+6ndthQSEDsSncFisnQ6NRTmUnhtAv8HX5qz8PJlnJTqXdRD8XoT83DNEahER/RE+5a1GMlaW/L6Nprf9Xu1bh5rD4rad8vtaaXjCYULv/bjWKPfdvjaZsDoT0k3otkkp+0PHkennXModNKuUZMYu2jT7bUH20NW6jsRjeZLQWEcQqM3Yq91+RqcebVruozazWRHhaNqxklVSrcezSDxJbStoC4Gj6Akt91FHTwCbEz9BJumPBdm9HSQETM2YNRkZf9yAslmdrxap7aoFwMQTAC+QEg+eOCiW58n4AqR+HZ441dy061Y3eHSQpTo/kVrq0iIqdhBYyquQiwitMRaC4cVAeR+5bZntPlF8jPuuVBj9omfHHVjT/o6PET/3wXu6rgSc3wSVoB/qff8duTF9QuqnFDJkXwQiTDCGaB88UVLiBL2rB3jW5WHtG6IHj6Qyx1jyfgLr7xlsks2RW3tFmmlggUxt+qDm30t6YhgKDVfNUImQ7y8un9NfYXls0ohxghJx2tsGf4gepey61H6ZrLY50xsl8c0jVj8ZqDymSZPl3lvamIuPgRvBwSPPiBsfqixE0XZmVpdTxSy/fghYtf6LAUDjG7OXf3xKiq6I=
  bucket: dinostroyed.agilehacker.com
  local-dir: build
  acl: public_read
  on:
    repo: kurtharriger/dinostroyed
